### ISSUE TITLE
Linux link errors when making examples

### ISSUE THREAD

**Issue by djtracy** [JoshuaBrookover/bgfx.cmake#3]
Various link errors occur when trying to 'make examples' in Linux (Ubuntu). Output attached.

[link_errors.txt](https://github.com/JoshuaBrookover/bgfx.cmake/files/791708/link_errors.txt)

**Comment by JoshuaBrookover** [comment]
Looks like examples need to link against X11, GL, pthread (maybe rt?), and dl. I don't have a Linux box to test the examples but I should be able to resolve the linker errors on a vps.

You can add the aforementioned libraries to the following line and it might fix it:
https://github.com/JoshuaBrookover/bgfx.cmake/blob/master/cmake/examples.cmake#L106

**Comment by djtracy** [comment]
Firstly, thank you for making bgfx.cmake!

Regarding the error, most of them are easy to resolve (X11, pthread, dl).
But I haven't been able to resolve the GL errors at all, which is stumping
my progress on my own project.

The link errors all refer to bgfx::gl::gl_functionNames(). Finding &
linking GL doesn't help. I tried adding a '::' prefix to calls and wrapping
their #include <GL> headers in 'extern "C"'. Doesn't seem to help. The link
errors then simply fail to find 'glEnd' rather than 'bgfx::gl::glEnd'.

If you have another idea of how I can proceed, I would appreciate it. It
all works on Mac OS X, but I'm trying to kick the closed-source habit and
move my environment to Linux.

Daniel

**Comment by JoshuaBrookover** [comment]
No problem, glad you find it useful. I am still at work, I will try to look into it tonight.

**Comment by JoshuaBrookover** [comment]
I have found the issue. glcontext_glx.cpp does indeed define all of the gl functions under bgfx::gl, so that much was correct. That particular file was being excluded from the build. That has been resolved along with pthreads/dl/GL/X11 being linked in the proper locations and a fix to shaderc failing due to missing directories: https://github.com/JoshuaBrookover/bgfx.cmake/commit/377ea644f1504ce14b15da91f7f7df10d86fe26b

I understand a few people have used bgfx.cmake on Linux already so I'm a bit surprised this wasn't noticed sooner.

Everything appears to be linking properly but I cannot run anything due to a lack of a graphics environment. Do let me know if the changes work out.

**Comment by djtracy** [comment]
It does indeed work beautifully in Linux. The graphics examples I tried
work great. Thanks!

However, you've broken the build in Mac OS X. Since 'UNIX' is also true for
Mac in CMake, I suggest the following fix:

bgfx.cmake line 54: if( UNIX AND NOT APPLE )

(mac chokes on -lGL)

Daniel

**Comment by JoshuaBrookover** [comment]
Ah, thanks for the heads up. I'll get that fixed up tonight.

**Comment by JoshuaBrookover** [comment]
https://github.com/JoshuaBrookover/bgfx.cmake/commit/8823f63b09d854f95ed3bec3f460d472965fb269

I think we're back in business.

**Comment by djtracy** [comment]
bgfx.cmake now compiles, & examples run, on macOS, ubuntu, & windows (VS2015).

Great! Thanks.
