### ISSUE TITLE
VS 2017 compile error, bimg header not found

### ISSUE THREAD

**Issue by VelocityRa** [JoshuaBrookover/bgfx.cmake#49]
I imported this to my project with
```cmake
add_subdirectory(bgfx.cmake)
```
And I'm getting this when trying to build:
```
11>image.cpp
11>D:\Nikos\Programming\cpp\pctation\external\bgfx.cmake\bimg\src\image.cpp(9): fatal error C1083: Cannot open include file: 'astc-codec/astc-codec.h': No such file or directory
```
no errors on CMake configure.

Generator is **Visual Studio 15 2017 Win64**, project files generated with cmake-gui.

The file exists and it's in `bgfx.cmake\bimg\3rdparty\astc-codec\include\astc-codec`, but that directory is not present in the bimg project's include dirs. Putting it manually in bimg Property Pages works, but of course that's not really a solution, CMake should handle this.

Also, after doing the above hack, linking fails because `ASTCDecompressToRGBA` which is defined in the above file is unresolved.

I'd appreciate any help, thanks.

**Comment by VelocityRa** [comment]
I switched to https://github.com/JoshuaBrookover/bigg and it works fine for some reason.

**Comment by JoshuaBrookover** [comment]
bigg is using a pretty old version of bgfx.cmake, and also an old version of bgfx/bimg, so that could be why that works. We do build VS in our travis CI so I do not think it is broken, this might be specific to linking in bgfx to another project, which I must admit that I do not attempt very often.

I was able to build it on OS X using this method. I will have to try on Windows later.

**Comment by VelocityRa** [comment]
I see, thanks.
