### ISSUE TITLE
CC0 license

### ISSUE THREAD

**Issue by bghgary** [JoshuaBrookover/bgfx.cmake#53]
It's quite unusual to have a CC0 license for source code. Is there any reason not to use a more typical license like MIT, BSD, etc.?

**Comment by JoshuaBrookover** [comment]
MIT and BSD have clauses imposing attribution (you must include the license and copyright). I want this code to be even less restrictive so that people may use it without that clause, as it is intended to be more of a starting point than an actual reuseable set of code (it's not a "library", necessarily).

CC0 is public domain with a fallback in the case that's not legally permissible. Also, for what its worth, [CC0 is recommended over unlicense and public domain by FSF for non-applications](https://www.gnu.org/licenses/license-list.en.html#Unlicense) (I consider CMake scripts not to be an application).

I am happy to work with you if you have any concerns about CC0. I chose it to impose the least amount of restrictions.
