### ISSUE TITLE
Install w/ Examples

### ISSUE THREAD

**Issue by xgalaxy** [JoshuaBrookover/bgfx.cmake#7]
Hello,

First off, thank you for putting this together. I was in the middle of creating my own about a year ago and lost track of time and just started coming back to it. On a whim I searched to see if anyone else had already done it and here we are! You managed to do far more than I could though - I'm not very well versed with CMake.

I think it would be helpful if you are building examples that INSTALL also created an examples folder in the install location with all the files necessary to run each example.

**Comment by JoshuaBrookover** [comment]
I wouldn't expect the install target for a library like this to install the examples. The install target is useful on certain platforms to quickly add them to the OS-specific designated areas for libs and includes and the like. I doubt anyone would expect that to also give them less relevant things like examples and all the assets required to run them.

That being said I have thought about improving my ConfigureDebugging.cmake script to be useful for more than just Visual Studio. If you haven't tried bgfx.cmake with Visual Studio, the examples all work when launching from there. Outside of Visual Studio, I'm not sure even the regular bgfx build system gives you much more than "make sure you're running from the proper working dir."

I could always add an optional cmake flag to have examples be installed, but I'm not sure that's the proper solution here.

**Comment by xgalaxy** [comment]
Hmm yea. It's been awhile but I think you are right about stock bgfx not making it easy to use the examples either.

While I've got your attention there is also something else I noticed. The stock bx/bgfx build scripts define certain compiler flags that you aren't handling:

```
# msvc
            /GR-        # no rtti
            /EHsc       # no exceptions ???
            /Oy         # no frame pointer
            /Z7         # symbols
            /GS-        # no buffer security check
            /O2         # optimize speed

# gcc/clang
            -fno-rtti            # no rtti
            -fno-exceptions      # no exceptions
            -fomit-frame-pointer # no frame pointer
            -g                   # symbols
            -fno-stack-protector # no buffer security check
            -O3                  # optimize speed
```

**Comment by JoshuaBrookover** [comment]
Yeah, that's partially intentional. I want to parody CMake's defaults as closely as possible, and allow people to optionally turn on some of those things (like no-exceptions) via the usual CMake means.

Although, last I checked there were 1 or 2 examples that crashed only when using bgfx.cmake, so could be related. I'll poke around at that a bit more at some point.

Any more thoughts on the original issue? I would love to simplify running the examples for non-VS build systems, only without hijacking INSTALL.

**Comment by xgalaxy** [comment]
My personal opinion is that if someone is choosing to have the examples built and choosing to 'install' then the examples should be installed as well. If they don't want the examples placed into the install location then they shouldn't choose to build them - or alter the install location to point to a non-system path.

Another option, is have a separate example-install location they can specify. If the examples are being built and they are choosing to 'install' but no example-install location is specified then keep the current behavior. But if they build the examples, are installing, and have an example-install location set then place the examples there along with all of the assets needed to run them properly.

Just my 2c.

**Comment by JoshuaBrookover** [comment]
I added BGFX_INSTALL_EXAMPLES which is off by default and will add the examples to the installation. I don't believe there is a way to have two installation directories in CMake. I prefer this solution because it means people won't accidentally install the examples, since they're on by default. I don't anticipate many people will use this anyway, it's pretty easy to do manually.

https://github.com/JoshuaBrookover/bgfx.cmake/commit/5ee179c940903faa98d28d86cf5c56eba1decb1d
