### ISSUE TITLE
WebGPU update

### ISSUE THREAD

**Issue by bwrsandman** [JoshuaBrookover/bgfx.cmake#78]
Recently, there has been a 3rdparty addition for bgfx.
This requires adding a cmake file for `3rdparty/webgpu` and linking it properly.

**Comment by pezcode** [comment]
Are you getting compile errors when trying to use other backends? Otherwise, I'd suggest waiting a little bit before implementing this, since the WebGPU backend is recent enough that there will likely still be changes in the bgfx build system. It's also missing recompiled shaders to be usable right now.

**Comment by bwrsandman** [comment]
Yes it fails to compile if updating the bgfx submodule

**Comment by pgruenbacher** [comment]
https://github.com/widberg/bgfx.cmake/pull/83 yea try this then.
